language: node_js
node_js:
    - "stable"

branches:
    only:
    - master
    - dev
    - staging

before_script:
    - npm install -g firebase-tools

script:
    - if [ "$TRAVIS_BRANCH" = "staging" ]; then
        firebase use staging;
        firebase deploy --project staging --token $FIREBASE_TOKEN;
      fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        firebase use prod;
        firebase deploy --project prod --token $FIREBASE_TOKEN;
      fi